datasource:
  class: house_prices_predictor.HousePricesDataSource

preparator:
  class: house_prices_predictor.HousePricesPreparator

algorithms:
  hp1: 
    class: house_prices_predictor.HousePricesPredictor
    params:
      model.pickle: ./output.pkl
  hp2: 
    class: house_prices_predictor.HousePricesPredictorRandom
    params:
      model.pickle: ./output_random.pkl

serving:
  class: house_prices_predictor.HousePricesServing

